
import { createClient } from '@supabase/supabase-js';

// Safely access env to prevent "Cannot read properties of undefined"
const env = (import.meta as any).env || {};

const supabaseUrl = env.VITE_SUPABASE_URL || 'https://pknfkxdpolvihwvzqrxy.supabase.co';
const supabaseKey = env.VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY || 'sb_publishable_cWkCHD6i3EJbAiVydA41cw_cByPr64s';

export const supabase = createClient(supabaseUrl, supabaseKey);

/* 
  SUPABASE SQL SCHEMA MIGRATION GUIDE:
  
  -- 1. Players Table
  create table public.players (
    id uuid references auth.users not null primary key,
    fb_user_id text unique,
    username text,
    avatar_url text,
    gold bigint default 0,
    streak int default 0,
    last_login timestamp with time zone,
    quests jsonb default '[]'::jsonb,
    artifacts jsonb[] default array[]::jsonb[],
    high_score bigint default 0,
    created_at timestamp with time zone default timezone('utc'::text, now())
  );
  
  -- 2. Leaderboards
  create table public.leaderboards (
    id bigint generated by default as identity primary key,
    player_id uuid references public.players not null,
    score bigint not null,
    tier int default 0,
    created_at timestamp with time zone default timezone('utc'::text, now())
  );

  -- 3. Daily Tributes (Loss Aversion)
  create table public.daily_tributes (
    id bigint generated by default as identity primary key,
    player_id uuid references public.players not null,
    amount int default 100,
    protected boolean default false,
    expires_at timestamp with time zone
  );

  -- 4. Gifts (Social)
  create table public.gifts (
    id bigint generated by default as identity primary key,
    from_id uuid references public.players not null,
    to_id uuid references public.players not null,
    mana int default 5,
    claimed boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now())
  );

  -- RLS Policies
  alter table public.players enable row level security;
  create policy "Public profiles are viewable by everyone." on public.players for select using (true);
  create policy "Users can insert their own profile." on public.players for insert with check (auth.uid() = id);
  create policy "Users can update own profile." on public.players for update using (auth.uid() = id);
*/
